# Use the official OpenJDK base image with the desired Java version
FROM openjdk:latest

# Set a working directory within the container
WORKDIR /app

# Copy the Java source code and resources into the container
COPY . /app

# Compile the Java application
RUN javac javaapp.java

# Specify the command to run your Java application
CMD ["java", "javaapp"]
